// <auto-generated />
namespace myLiteBoxMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class depIdtoint2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(depIdtoint2));
        
        string IMigrationMetadata.Id
        {
            get { return "201805022145597_depId to int2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
